module.exports = {
  ABSTRACT: true,
  STRING: true,
  CHAR: true,
  TEXT: true,
  NUMBER: true,
  TINYINT: true,
  SMALLINT: true,
  MEDIUMINT: true,
  INTEGER: true,
  BIGINT: true,
  FLOAT: true,
  REAL: true,
  DOUBLE: true,
  DECIMAL: true,
  BOOLEAN: true,
  TIME: true,
  DATE: true,
  DATEONLY: true,
  HSTORE: true,
  JSON: true,
  JSONB: true,
  NOW: true,
  BLOB: true,
  RANGE: true,
  UUID: true,
  UUIDV1: true,
  UUIDV4: true,
  VIRTUAL: true,
  ENUM: () => {},
  ARRAY: true,
  GEOMETRY: true,
  GEOGRAPHY: true,
  CIDR: true,
  INET: true,
  MACADDR: true,
  CITEXT: true
};
